### ISSUE TITLE
Macos M1 Bigsur 11.5.1 启动闪退

### ISSUE THREAD

**Issue by diduweiwu** [HarryWang29/tencentKeTang#10]
在config.yaml中已经配置了ffmpeg的目录，但是启动就报ffmpeg异常 不确定是不是m1芯片导致的

**Comment by HarryWang29** [comment]
填写的参数看下？

**Comment by xtray** [comment]
> 在config.yaml中已经配置了ffmpeg的目录，但是启动就报ffmpeg异常 不确定是不是m1芯片导致的，附错误消息
> 
> panic: 调用ffmpeg出错，请检查地址: exec.Run: signal: abort trap
> 
> goroutine 1 [running]:
> crawler/tencentKeTang/config.NewApp(0x1b)
> /Users/harry/app/go/src/crawler/tencentKeTang/config/app.go:33 +0x2ed
> main.main()
> /Users/harry/app/go/src/crawler/tencentKeTang/main.go:25 +0x34

https://blog.csdn.net/bobbob32/article/details/113525986

m1 芯片要自己重新编译 ffmpeg 就好了
